const teams = [
  {
    name: "Alex Caruso",
    team_acronym: "lal",
    team_name: "Lakers",
    games_played: "16",
    minutes_per_game: "12:43",
    field_goals_attempted_per_game: "2.3",
    field_goals_made_per_game: "1.0",
    field_goal_percentage: "43.2",
    free_throw_percentage: "20.0",
    three_point_attempted_per_game: "0.7",
    three_point_made_per_game: "0.3",
    three_point_percentage: "36.4",
    points_per_game: "2.3",
    offensive_rebounds_per_game: "0.3",
    defensive_rebounds_per_game: "0.8",
    rebounds_per_game: "1.1",
    assists_per_game: "1.6",
    steals_per_game: "0.4",
    blocks_per_game: "0.1",
    turnovers_per_game: "0.6",
    player_efficiency_rating: "1.2",
  },
  {
    name: "Andrew Bogut",
    team_acronym: "lal",
    team_name: "Lakers",
    games_played: "24",
    minutes_per_game: "9:01",
    field_goals_attempted_per_game: "1.0",
    field_goals_made_per_game: "0.7",
    field_goal_percentage: "68.0",
    free_throw_percentage: "100.0",
    three_point_attempted_per_game: "0.0",
    three_point_made_per_game: "0.0",
    three_point_percentage: "0.0",
    points_per_game: "1.5",
    offensive_rebounds_per_game: "1.1",
    defensive_rebounds_per_game: "2.2",
    rebounds_per_game: "3.3",
    assists_per_game: "0.6",
    steals_per_game: "0.2",
    blocks_per_game: "0.5",
    turnovers_per_game: "0.8",
    player_efficiency_rating: "1.7",
  },
  {
    name: "Brandon Ingram",
    team_acronym: "lal",
    team_name: "Lakers",
    games_played: "43",
    minutes_per_game: "33:44",
    field_goals_attempted_per_game: "12.8",
    field_goals_made_per_game: "5.8",
    field_goal_percentage: "45.1",
    free_throw_percentage: "67.8",
    three_point_attempted_per_game: "1.6",
    three_point_made_per_game: "0.6",
    three_point_percentage: "34.3",
    points_per_game: "15.5",
    offensive_rebounds_per_game: "1.0",
    defensive_rebounds_per_game: "4.3",
    rebounds_per_game: "5.3",
    assists_per_game: "3.4",
    steals_per_game: "0.8",
    blocks_per_game: "0.7",
    turnovers_per_game: "2.6",
    player_efficiency_rating: "2.8",
  },
  {
    name: "Brook Lopez",
    team_acronym: "lal",
    team_name: "Lakers",
    games_played: "39",
    minutes_per_game: "21:04",
    field_goals_attempted_per_game: "10.1",
    field_goals_made_per_game: "4.4",
    field_goal_percentage: "43.7",
    free_throw_percentage: "70.6",
    three_point_attempted_per_game: "4.3",
    three_point_made_per_game: "1.4",
    three_point_percentage: "31.5",
    points_per_game: "11.7",
    offensive_rebounds_per_game: "1.1",
    defensive_rebounds_per_game: "2.8",
    rebounds_per_game: "3.9",
    assists_per_game: "1.6",
    steals_per_game: "0.5",
    blocks_per_game: "1.3",
    turnovers_per_game: "1.6",
    player_efficiency_rating: "2.6",
  },
  {
    name: "Corey Brewer",
    team_acronym: "lal",
    team_name: "Lakers",
    games_played: "45",
    minutes_per_game: "12:41",
    field_goals_attempted_per_game: "3.0",
    field_goals_made_per_game: "1.4",
    field_goal_percentage: "44.9",
    free_throw_percentage: "65.1",
    three_point_attempted_per_game: "0.9",
    three_point_made_per_game: "0.2",
    three_point_percentage: "19.5",
    points_per_game: "3.5",
    offensive_rebounds_per_game: "0.3",
    defensive_rebounds_per_game: "1.3",
    rebounds_per_game: "1.6",
    assists_per_game: "0.7",
    steals_per_game: "0.8",
    blocks_per_game: "0.2",
    turnovers_per_game: "0.7",
    player_efficiency_rating: "1.5",
  },
  {
    name: "Ivica Zubac",
    team_acronym: "lal",
    team_name: "Lakers",
    games_played: "13",
    minutes_per_game: "3:41",
    field_goals_attempted_per_game: "1.1",
    field_goals_made_per_game: "0.5",
    field_goal_percentage: "42.9",
    free_throw_percentage: "0.0",
    three_point_attempted_per_game: "0.0",
    three_point_made_per_game: "0.0",
    three_point_percentage: "0.0",
    points_per_game: "0.9",
    offensive_rebounds_per_game: "0.2",
    defensive_rebounds_per_game: "0.5",
    rebounds_per_game: "0.8",
    assists_per_game: "0.1",
    steals_per_game: "0.0",
    blocks_per_game: "0.0",
    turnovers_per_game: "0.4",
    player_efficiency_rating: "0.4",
  },
  {
    name: "Jordan Clarkson",
    team_acronym: "lal",
    team_name: "Lakers",
    games_played: "47",
    minutes_per_game: "23:28",
    field_goals_attempted_per_game: "12.5",
    field_goals_made_per_game: "5.7",
    field_goal_percentage: "45.7",
    free_throw_percentage: "76.6",
    three_point_attempted_per_game: "3.8",
    three_point_made_per_game: "1.2",
    three_point_percentage: "32.4",
    points_per_game: "14.4",
    offensive_rebounds_per_game: "0.9",
    defensive_rebounds_per_game: "2.1",
    rebounds_per_game: "3.0",
    assists_per_game: "3.3",
    steals_per_game: "0.7",
    blocks_per_game: "0.0",
    turnovers_per_game: "1.7",
    player_efficiency_rating: "1.1",
  },
  {
    name: "Josh Hart",
    team_acronym: "lal",
    team_name: "Lakers",
    games_played: "42",
    minutes_per_game: "19:17",
    field_goals_attempted_per_game: "4.6",
    field_goals_made_per_game: "2.0",
    field_goal_percentage: "43.8",
    free_throw_percentage: "68.3",
    three_point_attempted_per_game: "2.4",
    three_point_made_per_game: "0.9",
    three_point_percentage: "35.6",
    points_per_game: "5.6",
    offensive_rebounds_per_game: "0.4",
    defensive_rebounds_per_game: "2.6",
    rebounds_per_game: "3.0",
    assists_per_game: "1.0",
    steals_per_game: "0.7",
    blocks_per_game: "0.2",
    turnovers_per_game: "0.5",
    player_efficiency_rating: "1.6",
  },
  {
    name: "Julius Randle",
    team_acronym: "lal",
    team_name: "Lakers",
    games_played: "47",
    minutes_per_game: "23:18",
    field_goals_attempted_per_game: "9.6",
    field_goals_made_per_game: "5.3",
    field_goal_percentage: "55.1",
    free_throw_percentage: "68.4",
    three_point_attempted_per_game: "0.7",
    three_point_made_per_game: "0.2",
    three_point_percentage: "22.9",
    points_per_game: "13.6",
    offensive_rebounds_per_game: "2.0",
    defensive_rebounds_per_game: "5.3",
    rebounds_per_game: "7.2",
    assists_per_game: "2.0",
    steals_per_game: "0.5",
    blocks_per_game: "0.7",
    turnovers_per_game: "2.3",
    player_efficiency_rating: "3.3",
  },
  {
    name: "Kentavious Caldwell-Pope",
    team_acronym: "lal",
    team_name: "Lakers",
    games_played: "39",
    minutes_per_game: "33:09",
    field_goals_attempted_per_game: "11.4",
    field_goals_made_per_game: "4.7",
    field_goal_percentage: "41.3",
    free_throw_percentage: "75.5",
    three_point_attempted_per_game: "5.8",
    three_point_made_per_game: "2.1",
    three_point_percentage: "35.7",
    points_per_game: "13.5",
    offensive_rebounds_per_game: "0.8",
    defensive_rebounds_per_game: "4.0",
    rebounds_per_game: "4.8",
    assists_per_game: "2.0",
    steals_per_game: "1.7",
    blocks_per_game: "0.3",
    turnovers_per_game: "1.4",
    player_efficiency_rating: "1.7",
  },
  {
    name: "Kyle Kuzma",
    team_acronym: "lal",
    team_name: "Lakers",
    games_played: "46",
    minutes_per_game: "30:39",
    field_goals_attempted_per_game: "13.6",
    field_goals_made_per_game: "6.3",
    field_goal_percentage: "46.3",
    free_throw_percentage: "70.7",
    three_point_attempted_per_game: "5.4",
    three_point_made_per_game: "2.1",
    three_point_percentage: "38.2",
    points_per_game: "16.7",
    offensive_rebounds_per_game: "1.3",
    defensive_rebounds_per_game: "4.7",
    rebounds_per_game: "6.0",
    assists_per_game: "1.9",
    steals_per_game: "0.5",
    blocks_per_game: "0.4",
    turnovers_per_game: "1.9",
    player_efficiency_rating: "2.2",
  },
  {
    name: "Larry Nance Jr.",
    team_acronym: "lal",
    team_name: "Lakers",
    games_played: "36",
    minutes_per_game: "22:22",
    field_goals_attempted_per_game: "6.3",
    field_goals_made_per_game: "3.8",
    field_goal_percentage: "60.2",
    free_throw_percentage: "61.0",
    three_point_attempted_per_game: "0.1",
    three_point_made_per_game: "0.0",
    three_point_percentage: "0.0",
    points_per_game: "8.9",
    offensive_rebounds_per_game: "2.5",
    defensive_rebounds_per_game: "4.3",
    rebounds_per_game: "6.8",
    assists_per_game: "1.4",
    steals_per_game: "1.4",
    blocks_per_game: "0.5",
    turnovers_per_game: "1.0",
    player_efficiency_rating: "2.8",
  },
  {
    name: "Lonzo Ball",
    team_acronym: "lal",
    team_name: "Lakers",
    games_played: "36",
    minutes_per_game: "33:56",
    field_goals_attempted_per_game: "11.1",
    field_goals_made_per_game: "3.9",
    field_goal_percentage: "35.6",
    free_throw_percentage: "48.0",
    three_point_attempted_per_game: "5.4",
    three_point_made_per_game: "1.6",
    three_point_percentage: "30.3",
    points_per_game: "10.2",
    offensive_rebounds_per_game: "1.3",
    defensive_rebounds_per_game: "5.8",
    rebounds_per_game: "7.1",
    assists_per_game: "7.1",
    steals_per_game: "1.5",
    blocks_per_game: "0.9",
    turnovers_per_game: "2.7",
    player_efficiency_rating: "2.2",
  },
  {
    name: "Luol Deng",
    team_acronym: "lal",
    team_name: "Lakers",
    games_played: "1",
    minutes_per_game: "13:08",
    field_goals_attempted_per_game: "2.0",
    field_goals_made_per_game: "1.0",
    field_goal_percentage: "50.0",
    free_throw_percentage: "0.0",
    three_point_attempted_per_game: "0.0",
    three_point_made_per_game: "0.0",
    three_point_percentage: "0.0",
    points_per_game: "2.0",
    offensive_rebounds_per_game: "0.0",
    defensive_rebounds_per_game: "0.0",
    rebounds_per_game: "0.0",
    assists_per_game: "1.0",
    steals_per_game: "1.0",
    blocks_per_game: "0.0",
    turnovers_per_game: "1.0",
    player_efficiency_rating: "0.0",
  },
  {
    name: "Nigel Hayes",
    team_acronym: "lal",
    team_name: "Lakers",
    games_played: "1",
    minutes_per_game: "1:01",
    field_goals_attempted_per_game: "0.0",
    field_goals_made_per_game: "0.0",
    field_goal_percentage: "0.0",
    free_throw_percentage: "0.0",
    three_point_attempted_per_game: "0.0",
    three_point_made_per_game: "0.0",
    three_point_percentage: "0.0",
    points_per_game: "0.0",
    offensive_rebounds_per_game: "0.0",
    defensive_rebounds_per_game: "0.0",
    rebounds_per_game: "0.0",
    assists_per_game: "0.0",
    steals_per_game: "0.0",
    blocks_per_game: "0.0",
    turnovers_per_game: "0.0",
    player_efficiency_rating: "0.0",
  },
  {
    name: "Thomas Bryant",
    team_acronym: "lal",
    team_name: "Lakers",
    games_played: "4",
    minutes_per_game: "1:51",
    field_goals_attempted_per_game: "0.5",
    field_goals_made_per_game: "0.3",
    field_goal_percentage: "50.0",
    free_throw_percentage: "50.0",
    three_point_attempted_per_game: "0.5",
    three_point_made_per_game: "0.3",
    three_point_percentage: "50.0",
    points_per_game: "1.0",
    offensive_rebounds_per_game: "0.0",
    defensive_rebounds_per_game: "0.3",
    rebounds_per_game: "0.3",
    assists_per_game: "0.0",
    steals_per_game: "0.0",
    blocks_per_game: "0.0",
    turnovers_per_game: "0.0",
    player_efficiency_rating: "0.0",
  },
  {
    name: "Tyler Ennis",
    team_acronym: "lal",
    team_name: "Lakers",
    games_played: "28",
    minutes_per_game: "11:21",
    field_goals_attempted_per_game: "3.6",
    field_goals_made_per_game: "1.4",
    field_goal_percentage: "37.6",
    free_throw_percentage: "75.0",
    three_point_attempted_per_game: "1.0",
    three_point_made_per_game: "0.2",
    three_point_percentage: "17.9",
    points_per_game: "3.3",
    offensive_rebounds_per_game: "0.3",
    defensive_rebounds_per_game: "1.1",
    rebounds_per_game: "1.4",
    assists_per_game: "2.0",
    steals_per_game: "0.4",
    blocks_per_game: "0.2",
    turnovers_per_game: "0.4",
    player_efficiency_rating: "1.5",
  },
  {
    name: "Vander Blue",
    team_acronym: "lal",
    team_name: "Lakers",
    games_played: "5",
    minutes_per_game: "8:59",
    field_goals_attempted_per_game: "1.0",
    field_goals_made_per_game: "0.2",
    field_goal_percentage: "20.0",
    free_throw_percentage: "50.0",
    three_point_attempted_per_game: "0.4",
    three_point_made_per_game: "0.0",
    three_point_percentage: "0.0",
    points_per_game: "0.6",
    offensive_rebounds_per_game: "0.0",
    defensive_rebounds_per_game: "0.2",
    rebounds_per_game: "0.2",
    assists_per_game: "0.6",
    steals_per_game: "0.2",
    blocks_per_game: "0.0",
    turnovers_per_game: "0.6",
    player_efficiency_rating: "0.4",
  },
  {
    name: "Andre Iguodala",
    team_acronym: "gsw",
    team_name: "Golden",
    games_played: "41",
    minutes_per_game: "25:43",
    field_goals_attempted_per_game: "5.1",
    field_goals_made_per_game: "2.2",
    field_goal_percentage: "43.1",
    free_throw_percentage: "62.9",
    three_point_attempted_per_game: "1.8",
    three_point_made_per_game: "0.4",
    three_point_percentage: "23.3",
    points_per_game: "5.8",
    offensive_rebounds_per_game: "0.9",
    defensive_rebounds_per_game: "3.0",
    rebounds_per_game: "3.8",
    assists_per_game: "3.4",
    steals_per_game: "0.8",
    blocks_per_game: "0.6",
    turnovers_per_game: "1.0",
    player_efficiency_rating: "1.5",
  },
  {
    name: "Damian Jones",
    team_acronym: "gsw",
    team_name: "Golden",
    games_played: "1",
    minutes_per_game: "1:48",
    field_goals_attempted_per_game: "0.0",
    field_goals_made_per_game: "0.0",
    field_goal_percentage: "0.0",
    free_throw_percentage: "0.0",
    three_point_attempted_per_game: "0.0",
    three_point_made_per_game: "0.0",
    three_point_percentage: "0.0",
    points_per_game: "0.0",
    offensive_rebounds_per_game: "1.0",
    defensive_rebounds_per_game: "0.0",
    rebounds_per_game: "1.0",
    assists_per_game: "0.0",
    steals_per_game: "0.0",
    blocks_per_game: "0.0",
    turnovers_per_game: "0.0",
    player_efficiency_rating: "1.0",
  },
  {
    name: "David West",
    team_acronym: "gsw",
    team_name: "Golden",
    games_played: "47",
    minutes_per_game: "13:17",
    field_goals_attempted_per_game: "5.1",
    field_goals_made_per_game: "3.1",
    field_goal_percentage: "60.8",
    free_throw_percentage: "71.2",
    three_point_attempted_per_game: "0.1",
    three_point_made_per_game: "0.1",
    three_point_percentage: "42.9",
    points_per_game: "7.1",
    offensive_rebounds_per_game: "0.9",
    defensive_rebounds_per_game: "2.5",
    rebounds_per_game: "3.4",
    assists_per_game: "1.8",
    steals_per_game: "0.6",
    blocks_per_game: "1.1",
    turnovers_per_game: "1.0",
    player_efficiency_rating: "1.6",
  },
  {
    name: "Draymond Green",
    team_acronym: "gsw",
    team_name: "Golden",
    games_played: "42",
    minutes_per_game: "32:23",
    field_goals_attempted_per_game: "8.7",
    field_goals_made_per_game: "4.0",
    field_goal_percentage: "46.4",
    free_throw_percentage: "77.5",
    three_point_attempted_per_game: "3.8",
    three_point_made_per_game: "1.2",
    three_point_percentage: "31.1",
    points_per_game: "11.3",
    offensive_rebounds_per_game: "1.1",
    defensive_rebounds_per_game: "6.8",
    rebounds_per_game: "7.8",
    assists_per_game: "7.4",
    steals_per_game: "1.3",
    blocks_per_game: "1.3",
    turnovers_per_game: "2.7",
    player_efficiency_rating: "2.5",
  },
  {
    name: "JaVale McGee",
    team_acronym: "gsw",
    team_name: "Golden",
    games_played: "34",
    minutes_per_game: "7:52",
    field_goals_attempted_per_game: "2.6",
    field_goals_made_per_game: "1.6",
    field_goal_percentage: "61.8",
    free_throw_percentage: "76.0",
    three_point_attempted_per_game: "0.1",
    three_point_made_per_game: "0.0",
    three_point_percentage: "0.0",
    points_per_game: "3.8",
    offensive_rebounds_per_game: "0.7",
    defensive_rebounds_per_game: "1.1",
    rebounds_per_game: "1.8",
    assists_per_game: "0.5",
    steals_per_game: "0.3",
    blocks_per_game: "0.7",
    turnovers_per_game: "0.4",
    player_efficiency_rating: "1.1",
  },
  {
    name: "Jordan Bell",
    team_acronym: "gsw",
    team_name: "Golden",
    games_played: "38",
    minutes_per_game: "14:22",
    field_goals_attempted_per_game: "3.4",
    field_goals_made_per_game: "2.3",
    field_goal_percentage: "66.4",
    free_throw_percentage: "66.7",
    three_point_attempted_per_game: "0.1",
    three_point_made_per_game: "0.0",
    three_point_percentage: "0.0",
    points_per_game: "5.1",
    offensive_rebounds_per_game: "1.2",
    defensive_rebounds_per_game: "2.7",
    rebounds_per_game: "3.9",
    assists_per_game: "1.8",
    steals_per_game: "0.7",
    blocks_per_game: "1.1",
    turnovers_per_game: "1.0",
    player_efficiency_rating: "1.9",
  },
  {
    name: "Kevin Durant",
    team_acronym: "gsw",
    team_name: "Golden",
    games_played: "41",
    minutes_per_game: "34:44",
    field_goals_attempted_per_game: "18.2",
    field_goals_made_per_game: "9.3",
    field_goal_percentage: "51.1",
    free_throw_percentage: "89.0",
    three_point_attempted_per_game: "6.2",
    three_point_made_per_game: "2.6",
    three_point_percentage: "42.0",
    points_per_game: "26.0",
    offensive_rebounds_per_game: "0.5",
    defensive_rebounds_per_game: "6.4",
    rebounds_per_game: "7.0",
    assists_per_game: "5.7",
    steals_per_game: "0.9",
    blocks_per_game: "2.1",
    turnovers_per_game: "3.2",
    player_efficiency_rating: "2.2",
  },
  {
    name: "Kevon Looney",
    team_acronym: "gsw",
    team_name: "Golden",
    games_played: "39",
    minutes_per_game: "11:08",
    field_goals_attempted_per_game: "2.0",
    field_goals_made_per_game: "1.2",
    field_goal_percentage: "60.8",
    free_throw_percentage: "60.0",
    three_point_attempted_per_game: "0.0",
    three_point_made_per_game: "0.0",
    three_point_percentage: "0.0",
    points_per_game: "3.1",
    offensive_rebounds_per_game: "1.1",
    defensive_rebounds_per_game: "1.7",
    rebounds_per_game: "2.8",
    assists_per_game: "0.5",
    steals_per_game: "0.3",
    blocks_per_game: "0.6",
    turnovers_per_game: "0.5",
    player_efficiency_rating: "1.4",
  },
  {
    name: "Klay Thompson",
    team_acronym: "gsw",
    team_name: "Golden",
    games_played: "48",
    minutes_per_game: "34:17",
    field_goals_attempted_per_game: "16.3",
    field_goals_made_per_game: "7.9",
    field_goal_percentage: "48.8",
    free_throw_percentage: "87.0",
    three_point_attempted_per_game: "7.3",
    three_point_made_per_game: "3.4",
    three_point_percentage: "45.7",
    points_per_game: "20.5",
    offensive_rebounds_per_game: "0.4",
    defensive_rebounds_per_game: "3.5",
    rebounds_per_game: "4.0",
    assists_per_game: "2.5",
    steals_per_game: "0.7",
    blocks_per_game: "0.6",
    turnovers_per_game: "1.7",
    player_efficiency_rating: "1.7",
  },
  {
    name: "Nick Young",
    team_acronym: "gsw",
    team_name: "Golden",
    games_played: "47",
    minutes_per_game: "14:32",
    field_goals_attempted_per_game: "5.4",
    field_goals_made_per_game: "2.4",
    field_goal_percentage: "44.9",
    free_throw_percentage: "71.4",
    three_point_attempted_per_game: "3.7",
    three_point_made_per_game: "1.4",
    three_point_percentage: "39.1",
    points_per_game: "6.7",
    offensive_rebounds_per_game: "0.2",
    defensive_rebounds_per_game: "1.0",
    rebounds_per_game: "1.2",
    assists_per_game: "0.4",
    steals_per_game: "0.4",
    blocks_per_game: "0.1",
    turnovers_per_game: "0.4",
    player_efficiency_rating: "1.2",
  },
  {
    name: "Omri Casspi",
    team_acronym: "gsw",
    team_name: "Golden",
    games_played: "37",
    minutes_per_game: "16:04",
    field_goals_attempted_per_game: "4.4",
    field_goals_made_per_game: "2.6",
    field_goal_percentage: "59.9",
    free_throw_percentage: "78.2",
    three_point_attempted_per_game: "0.5",
    three_point_made_per_game: "0.2",
    three_point_percentage: "50.0",
    points_per_game: "6.6",
    offensive_rebounds_per_game: "0.6",
    defensive_rebounds_per_game: "3.6",
    rebounds_per_game: "4.2",
    assists_per_game: "1.1",
    steals_per_game: "0.4",
    blocks_per_game: "0.5",
    turnovers_per_game: "0.8",
    player_efficiency_rating: "1.5",
  },
  {
    name: "Patrick McCaw",
    team_acronym: "gsw",
    team_name: "Golden",
    games_played: "44",
    minutes_per_game: "16:13",
    field_goals_attempted_per_game: "3.6",
    field_goals_made_per_game: "1.6",
    field_goal_percentage: "45.3",
    free_throw_percentage: "72.0",
    three_point_attempted_per_game: "1.3",
    three_point_made_per_game: "0.3",
    three_point_percentage: "25.4",
    points_per_game: "4.0",
    offensive_rebounds_per_game: "0.3",
    defensive_rebounds_per_game: "1.2",
    rebounds_per_game: "1.5",
    assists_per_game: "1.4",
    steals_per_game: "0.8",
    blocks_per_game: "0.2",
    turnovers_per_game: "0.6",
    player_efficiency_rating: "1.1",
  },
  {
    name: "Quinn Cook",
    team_acronym: "gsw",
    team_name: "Golden",
    games_played: "10",
    minutes_per_game: "10:18",
    field_goals_attempted_per_game: "2.9",
    field_goals_made_per_game: "1.3",
    field_goal_percentage: "44.8",
    free_throw_percentage: "100.0",
    three_point_attempted_per_game: "1.4",
    three_point_made_per_game: "0.5",
    three_point_percentage: "35.7",
    points_per_game: "3.2",
    offensive_rebounds_per_game: "0.2",
    defensive_rebounds_per_game: "0.9",
    rebounds_per_game: "1.1",
    assists_per_game: "1.6",
    steals_per_game: "0.0",
    blocks_per_game: "0.0",
    turnovers_per_game: "0.3",
    player_efficiency_rating: "0.9",
  },
  {
    name: "Shaun Livingston",
    team_acronym: "gsw",
    team_name: "Golden",
    games_played: "42",
    minutes_per_game: "15:46",
    field_goals_attempted_per_game: "4.6",
    field_goals_made_per_game: "2.4",
    field_goal_percentage: "51.0",
    free_throw_percentage: "77.8",
    three_point_attempted_per_game: "0.0",
    three_point_made_per_game: "0.0",
    three_point_percentage: "0.0",
    points_per_game: "5.4",
    offensive_rebounds_per_game: "0.5",
    defensive_rebounds_per_game: "1.3",
    rebounds_per_game: "1.8",
    assists_per_game: "2.0",
    steals_per_game: "0.4",
    blocks_per_game: "0.3",
    turnovers_per_game: "0.8",
    player_efficiency_rating: "1.6",
  },
  {
    name: "Stephen Curry",
    team_acronym: "gsw",
    team_name: "Golden",
    games_played: "34",
    minutes_per_game: "32:58",
    field_goals_attempted_per_game: "17.6",
    field_goals_made_per_game: "8.6",
    field_goal_percentage: "49.2",
    free_throw_percentage: "91.0",
    three_point_attempted_per_game: "10.1",
    three_point_made_per_game: "4.3",
    three_point_percentage: "42.3",
    points_per_game: "27.5",
    offensive_rebounds_per_game: "0.6",
    defensive_rebounds_per_game: "4.6",
    rebounds_per_game: "5.2",
    assists_per_game: "6.6",
    steals_per_game: "1.6",
    blocks_per_game: "0.1",
    turnovers_per_game: "2.9",
    player_efficiency_rating: "2.4",
  },
  {
    name: "Zaza Pachulia",
    team_acronym: "gsw",
    team_name: "Golden",
    games_played: "39",
    minutes_per_game: "14:36",
    field_goals_attempted_per_game: "4.0",
    field_goals_made_per_game: "2.4",
    field_goal_percentage: "59.4",
    free_throw_percentage: "84.0",
    three_point_attempted_per_game: "0.0",
    three_point_made_per_game: "0.0",
    three_point_percentage: "0.0",
    points_per_game: "5.8",
    offensive_rebounds_per_game: "1.0",
    defensive_rebounds_per_game: "3.7",
    rebounds_per_game: "4.7",
    assists_per_game: "1.7",
    steals_per_game: "0.6",
    blocks_per_game: "0.2",
    turnovers_per_game: "1.1",
    player_efficiency_rating: "1.8",
  },
  {
    name: "Amir Johnson",
    team_acronym: "phi",
    team_name: "Philadelphia",
    games_played: "41",
    minutes_per_game: "15:23",
    field_goals_attempted_per_game: "3.7",
    field_goals_made_per_game: "2.0",
    field_goal_percentage: "53.3",
    free_throw_percentage: "60.4",
    three_point_attempted_per_game: "0.4",
    three_point_made_per_game: "0.1",
    three_point_percentage: "25.0",
    points_per_game: "4.8",
    offensive_rebounds_per_game: "1.9",
    defensive_rebounds_per_game: "2.9",
    rebounds_per_game: "4.7",
    assists_per_game: "1.4",
    steals_per_game: "0.7",
    blocks_per_game: "0.7",
    turnovers_per_game: "0.8",
    player_efficiency_rating: "2.7",
  },
  {
    name: "Ben Simmons",
    team_acronym: "phi",
    team_name: "Philadelphia",
    games_played: "43",
    minutes_per_game: "35:05",
    field_goals_attempted_per_game: "13.5",
    field_goals_made_per_game: "6.9",
    field_goal_percentage: "50.9",
    free_throw_percentage: "56.3",
    three_point_attempted_per_game: "0.2",
    three_point_made_per_game: "0.0",
    three_point_percentage: "0.0",
    points_per_game: "16.4",
    offensive_rebounds_per_game: "1.8",
    defensive_rebounds_per_game: "6.3",
    rebounds_per_game: "8.1",
    assists_per_game: "7.4",
    steals_per_game: "1.8",
    blocks_per_game: "0.9",
    turnovers_per_game: "4.0",
    player_efficiency_rating: "3.0",
  },
  {
    name: "Dario Saric",
    team_acronym: "phi",
    team_name: "Philadelphia",
    games_played: "43",
    minutes_per_game: "30:37",
    field_goals_attempted_per_game: "11.3",
    field_goals_made_per_game: "5.0",
    field_goal_percentage: "44.2",
    free_throw_percentage: "89.1",
    three_point_attempted_per_game: "4.9",
    three_point_made_per_game: "1.9",
    three_point_percentage: "37.7",
    points_per_game: "14.0",
    offensive_rebounds_per_game: "2.1",
    defensive_rebounds_per_game: "4.8",
    rebounds_per_game: "7.0",
    assists_per_game: "2.7",
    steals_per_game: "0.7",
    blocks_per_game: "0.3",
    turnovers_per_game: "2.0",
    player_efficiency_rating: "2.1",
  },
  {
    name: "Furkan Korkmaz",
    team_acronym: "phi",
    team_name: "Philadelphia",
    games_played: "6",
    minutes_per_game: "5:19",
    field_goals_attempted_per_game: "2.0",
    field_goals_made_per_game: "0.5",
    field_goal_percentage: "25.0",
    free_throw_percentage: "100.0",
    three_point_attempted_per_game: "1.3",
    three_point_made_per_game: "0.2",
    three_point_percentage: "12.5",
    points_per_game: "1.5",
    offensive_rebounds_per_game: "0.3",
    defensive_rebounds_per_game: "0.7",
    rebounds_per_game: "1.0",
    assists_per_game: "0.3",
    steals_per_game: "0.2",
    blocks_per_game: "0.0",
    turnovers_per_game: "0.2",
    player_efficiency_rating: "0.7",
  },
  {
    name: "Jacob Pullen",
    team_acronym: "phi",
    team_name: "Philadelphia",
    games_played: "3",
    minutes_per_game: "2:01",
    field_goals_attempted_per_game: "0.7",
    field_goals_made_per_game: "0.3",
    field_goal_percentage: "50.0",
    free_throw_percentage: "0.0",
    three_point_attempted_per_game: "0.3",
    three_point_made_per_game: "0.0",
    three_point_percentage: "0.0",
    points_per_game: "0.7",
    offensive_rebounds_per_game: "0.0",
    defensive_rebounds_per_game: "0.0",
    rebounds_per_game: "0.0",
    assists_per_game: "0.0",
    steals_per_game: "0.0",
    blocks_per_game: "0.0",
    turnovers_per_game: "0.3",
    player_efficiency_rating: "0.0",
  },
  {
    name: "Jahlil Okafor",
    team_acronym: "phi",
    team_name: "Philadelphia",
    games_played: "2",
    minutes_per_game: "12:38",
    field_goals_attempted_per_game: "4.5",
    field_goals_made_per_game: "2.0",
    field_goal_percentage: "44.4",
    free_throw_percentage: "50.0",
    three_point_attempted_per_game: "0.0",
    three_point_made_per_game: "0.0",
    three_point_percentage: "0.0",
    points_per_game: "5.0",
    offensive_rebounds_per_game: "2.0",
    defensive_rebounds_per_game: "2.5",
    rebounds_per_game: "4.5",
    assists_per_game: "0.5",
    steals_per_game: "0.0",
    blocks_per_game: "1.0",
    turnovers_per_game: "1.5",
    player_efficiency_rating: "3.5",
  },
  {
    name: "James Michael McAdoo",
    team_acronym: "phi",
    team_name: "Philadelphia",
    games_played: "3",
    minutes_per_game: "5:59",
    field_goals_attempted_per_game: "2.3",
    field_goals_made_per_game: "0.7",
    field_goal_percentage: "28.6",
    free_throw_percentage: "100.0",
    three_point_attempted_per_game: "2.3",
    three_point_made_per_game: "0.7",
    three_point_percentage: "28.6",
    points_per_game: "2.7",
    offensive_rebounds_per_game: "0.0",
    defensive_rebounds_per_game: "0.7",
    rebounds_per_game: "0.7",
    assists_per_game: "0.0",
    steals_per_game: "0.0",
    blocks_per_game: "0.3",
    turnovers_per_game: "0.3",
    player_efficiency_rating: "0.3",
  },
  {
    name: "James Young",
    team_acronym: "phi",
    team_name: "Philadelphia",
    games_played: "2",
    minutes_per_game: "10:20",
    field_goals_attempted_per_game: "4.0",
    field_goals_made_per_game: "1.0",
    field_goal_percentage: "25.0",
    free_throw_percentage: "50.0",
    three_point_attempted_per_game: "3.5",
    three_point_made_per_game: "1.0",
    three_point_percentage: "28.6",
    points_per_game: "4.0",
    offensive_rebounds_per_game: "0.0",
    defensive_rebounds_per_game: "0.5",
    rebounds_per_game: "0.5",
    assists_per_game: "0.0",
    steals_per_game: "0.0",
    blocks_per_game: "0.0",
    turnovers_per_game: "0.0",
    player_efficiency_rating: "1.0",
  },
  {
    name: "Jerryd Bayless",
    team_acronym: "phi",
    team_name: "Philadelphia",
    games_played: "35",
    minutes_per_game: "24:51",
    field_goals_attempted_per_game: "7.0",
    field_goals_made_per_game: "2.9",
    field_goal_percentage: "41.9",
    free_throw_percentage: "79.5",
    three_point_attempted_per_game: "3.9",
    three_point_made_per_game: "1.5",
    three_point_percentage: "37.0",
    points_per_game: "8.3",
    offensive_rebounds_per_game: "0.4",
    defensive_rebounds_per_game: "1.8",
    rebounds_per_game: "2.2",
    assists_per_game: "1.4",
    steals_per_game: "0.7",
    blocks_per_game: "0.2",
    turnovers_per_game: "1.2",
    player_efficiency_rating: "2.5",
  },
  {
    name: "JJ Redick",
    team_acronym: "phi",
    team_name: "Philadelphia",
    games_played: "36",
    minutes_per_game: "32:34",
    field_goals_attempted_per_game: "13.0",
    field_goals_made_per_game: "5.8",
    field_goal_percentage: "44.8",
    free_throw_percentage: "94.6",
    three_point_attempted_per_game: "6.7",
    three_point_made_per_game: "2.7",
    three_point_percentage: "40.5",
    points_per_game: "17.3",
    offensive_rebounds_per_game: "0.2",
    defensive_rebounds_per_game: "2.6",
    rebounds_per_game: "2.8",
    assists_per_game: "3.3",
    steals_per_game: "0.5",
    blocks_per_game: "0.1",
    turnovers_per_game: "1.5",
    player_efficiency_rating: "2.1",
  },
  {
    name: "Joel Embiid",
    team_acronym: "phi",
    team_name: "Philadelphia",
    games_played: "35",
    minutes_per_game: "31:29",
    field_goals_attempted_per_game: "16.9",
    field_goals_made_per_game: "8.3",
    field_goal_percentage: "49.1",
    free_throw_percentage: "79.3",
    three_point_attempted_per_game: "3.1",
    three_point_made_per_game: "0.9",
    three_point_percentage: "29.0",
    points_per_game: "23.7",
    offensive_rebounds_per_game: "2.2",
    defensive_rebounds_per_game: "8.7",
    rebounds_per_game: "10.9",
    assists_per_game: "3.3",
    steals_per_game: "0.6",
    blocks_per_game: "1.9",
    turnovers_per_game: "4.1",
    player_efficiency_rating: "3.5",
  },
  {
    name: "Justin Anderson",
    team_acronym: "phi",
    team_name: "Philadelphia",
    games_played: "16",
    minutes_per_game: "12:57",
    field_goals_attempted_per_game: "5.0",
    field_goals_made_per_game: "1.9",
    field_goal_percentage: "38.8",
    free_throw_percentage: "72.7",
    three_point_attempted_per_game: "2.6",
    three_point_made_per_game: "0.8",
    three_point_percentage: "31.0",
    points_per_game: "5.2",
    offensive_rebounds_per_game: "0.9",
    defensive_rebounds_per_game: "1.6",
    rebounds_per_game: "2.5",
    assists_per_game: "0.4",
    steals_per_game: "0.3",
    blocks_per_game: "0.1",
    turnovers_per_game: "0.4",
    player_efficiency_rating: "1.5",
  },
  {
    name: "Larry Drew II",
    team_acronym: "phi",
    team_name: "Philadelphia",
    games_played: "1",
    minutes_per_game: "9:13",
    field_goals_attempted_per_game: "3.0",
    field_goals_made_per_game: "0.0",
    field_goal_percentage: "0.0",
    free_throw_percentage: "0.0",
    three_point_attempted_per_game: "2.0",
    three_point_made_per_game: "0.0",
    three_point_percentage: "0.0",
    points_per_game: "0.0",
    offensive_rebounds_per_game: "0.0",
    defensive_rebounds_per_game: "0.0",
    rebounds_per_game: "0.0",
    assists_per_game: "1.0",
    steals_per_game: "0.0",
    blocks_per_game: "0.0",
    turnovers_per_game: "0.0",
    player_efficiency_rating: "1.0",
  },
  {
    name: "Markelle Fultz",
    team_acronym: "phi",
    team_name: "Philadelphia",
    games_played: "4",
    minutes_per_game: "18:54",
    field_goals_attempted_per_game: "6.8",
    field_goals_made_per_game: "2.3",
    field_goal_percentage: "33.3",
    free_throw_percentage: "50.0",
    three_point_attempted_per_game: "0.0",
    three_point_made_per_game: "0.0",
    three_point_percentage: "0.0",
    points_per_game: "6.0",
    offensive_rebounds_per_game: "0.8",
    defensive_rebounds_per_game: "1.5",
    rebounds_per_game: "2.3",
    assists_per_game: "1.8",
    steals_per_game: "0.5",
    blocks_per_game: "0.3",
    turnovers_per_game: "1.5",
    player_efficiency_rating: "1.5",
  },
  {
    name: "Nik Stauskas",
    team_acronym: "phi",
    team_name: "Philadelphia",
    games_played: "6",
    minutes_per_game: "7:29",
    field_goals_attempted_per_game: "0.7",
    field_goals_made_per_game: "0.2",
    field_goal_percentage: "25.0",
    free_throw_percentage: "100.0",
    three_point_attempted_per_game: "0.2",
    three_point_made_per_game: "0.0",
    three_point_percentage: "0.0",
    points_per_game: "0.7",
    offensive_rebounds_per_game: "0.0",
    defensive_rebounds_per_game: "0.2",
    rebounds_per_game: "0.2",
    assists_per_game: "0.2",
    steals_per_game: "0.7",
    blocks_per_game: "0.0",
    turnovers_per_game: "0.7",
    player_efficiency_rating: "0.5",
  },
  {
    name: "Richaun Holmes",
    team_acronym: "phi",
    team_name: "Philadelphia",
    games_played: "23",
    minutes_per_game: "15:51",
    field_goals_attempted_per_game: "5.4",
    field_goals_made_per_game: "2.8",
    field_goal_percentage: "52.4",
    free_throw_percentage: "70.8",
    three_point_attempted_per_game: "0.9",
    three_point_made_per_game: "0.1",
    three_point_percentage: "15.0",
    points_per_game: "6.5",
    offensive_rebounds_per_game: "1.1",
    defensive_rebounds_per_game: "3.5",
    rebounds_per_game: "4.6",
    assists_per_game: "1.1",
    steals_per_game: "0.4",
    blocks_per_game: "0.4",
    turnovers_per_game: "0.6",
    player_efficiency_rating: "2.5",
  },
  {
    name: "Robert Covington",
    team_acronym: "phi",
    team_name: "Philadelphia",
    games_played: "42",
    minutes_per_game: "32:24",
    field_goals_attempted_per_game: "10.9",
    field_goals_made_per_game: "4.6",
    field_goal_percentage: "42.1",
    free_throw_percentage: "84.6",
    three_point_attempted_per_game: "7.2",
    three_point_made_per_game: "2.8",
    three_point_percentage: "38.9",
    points_per_game: "13.5",
    offensive_rebounds_per_game: "0.8",
    defensive_rebounds_per_game: "5.0",
    rebounds_per_game: "5.8",
    assists_per_game: "2.0",
    steals_per_game: "1.7",
    blocks_per_game: "0.7",
    turnovers_per_game: "1.9",
    player_efficiency_rating: "3.0",
  },
  {
    name: "Timothe Luwawu-Cabarrot",
    team_acronym: "phi",
    team_name: "Philadelphia",
    games_played: "40",
    minutes_per_game: "16:28",
    field_goals_attempted_per_game: "5.4",
    field_goals_made_per_game: "2.2",
    field_goal_percentage: "40.1",
    free_throw_percentage: "77.8",
    three_point_attempted_per_game: "3.2",
    three_point_made_per_game: "1.2",
    three_point_percentage: "35.9",
    points_per_game: "6.6",
    offensive_rebounds_per_game: "0.3",
    defensive_rebounds_per_game: "1.3",
    rebounds_per_game: "1.6",
    assists_per_game: "1.1",
    steals_per_game: "0.3",
    blocks_per_game: "0.1",
    turnovers_per_game: "0.8",
    player_efficiency_rating: "2.0",
  },
  {
    name: "T.J. McConnell",
    team_acronym: "phi",
    team_name: "Philadelphia",
    games_played: "38",
    minutes_per_game: "25:03",
    field_goals_attempted_per_game: "6.4",
    field_goals_made_per_game: "3.4",
    field_goal_percentage: "52.7",
    free_throw_percentage: "80.8",
    three_point_attempted_per_game: "1.0",
    three_point_made_per_game: "0.4",
    three_point_percentage: "43.6",
    points_per_game: "7.7",
    offensive_rebounds_per_game: "0.6",
    defensive_rebounds_per_game: "2.9",
    rebounds_per_game: "3.5",
    assists_per_game: "4.7",
    steals_per_game: "1.3",
    blocks_per_game: "0.3",
    turnovers_per_game: "2.0",
    player_efficiency_rating: "1.9",
  },
  {
    name: "Trevor Booker",
    team_acronym: "phi",
    team_name: "Philadelphia",
    games_played: "19",
    minutes_per_game: "14:48",
    field_goals_attempted_per_game: "3.5",
    field_goals_made_per_game: "2.1",
    field_goal_percentage: "58.2",
    free_throw_percentage: "83.3",
    three_point_attempted_per_game: "0.1",
    three_point_made_per_game: "0.0",
    three_point_percentage: "0.0",
    points_per_game: "5.2",
    offensive_rebounds_per_game: "1.6",
    defensive_rebounds_per_game: "2.2",
    rebounds_per_game: "3.7",
    assists_per_game: "0.8",
    steals_per_game: "0.5",
    blocks_per_game: "0.4",
    turnovers_per_game: "0.6",
    player_efficiency_rating: "1.3",
  },
  {
    name: "Bobby Brown",
    team_acronym: "hou",
    team_name: "Houston",
    games_played: "20",
    minutes_per_game: "5:44",
    field_goals_attempted_per_game: "2.9",
    field_goals_made_per_game: "1.0",
    field_goal_percentage: "32.8",
    free_throw_percentage: "50.0",
    three_point_attempted_per_game: "2.0",
    three_point_made_per_game: "0.6",
    three_point_percentage: "27.5",
    points_per_game: "2.5",
    offensive_rebounds_per_game: "0.0",
    defensive_rebounds_per_game: "0.4",
    rebounds_per_game: "0.4",
    assists_per_game: "0.6",
    steals_per_game: "0.2",
    blocks_per_game: "0.0",
    turnovers_per_game: "0.5",
    player_efficiency_rating: "0.3",
  },
  {
    name: "Briante Weber",
    team_acronym: "hou",
    team_name: "Houston",
    games_played: "13",
    minutes_per_game: "9:03",
    field_goals_attempted_per_game: "1.7",
    field_goals_made_per_game: "0.7",
    field_goal_percentage: "40.9",
    free_throw_percentage: "100.0",
    three_point_attempted_per_game: "0.7",
    three_point_made_per_game: "0.3",
    three_point_percentage: "44.4",
    points_per_game: "2.0",
    offensive_rebounds_per_game: "0.2",
    defensive_rebounds_per_game: "1.2",
    rebounds_per_game: "1.4",
    assists_per_game: "1.0",
    steals_per_game: "0.8",
    blocks_per_game: "0.2",
    turnovers_per_game: "0.5",
    player_efficiency_rating: "1.4",
  },
  {
    name: "Chris Paul",
    team_acronym: "hou",
    team_name: "Houston",
    games_played: "29",
    minutes_per_game: "32:13",
    field_goals_attempted_per_game: "14.1",
    field_goals_made_per_game: "6.4",
    field_goal_percentage: "45.3",
    free_throw_percentage: "90.5",
    three_point_attempted_per_game: "7.1",
    three_point_made_per_game: "2.8",
    three_point_percentage: "39.5",
    points_per_game: "18.8",
    offensive_rebounds_per_game: "0.7",
    defensive_rebounds_per_game: "5.2",
    rebounds_per_game: "5.9",
    assists_per_game: "8.8",
    steals_per_game: "1.9",
    blocks_per_game: "0.4",
    turnovers_per_game: "2.6",
    player_efficiency_rating: "2.5",
  },
  {
    name: "Clint Capela",
    team_acronym: "hou",
    team_name: "Houston",
    games_played: "41",
    minutes_per_game: "26:34",
    field_goals_attempted_per_game: "9.3",
    field_goals_made_per_game: "6.2",
    field_goal_percentage: "66.8",
    free_throw_percentage: "59.9",
    three_point_attempted_per_game: "0.0",
    three_point_made_per_game: "0.0",
    three_point_percentage: "0.0",
    points_per_game: "14.5",
    offensive_rebounds_per_game: "3.3",
    defensive_rebounds_per_game: "7.5",
    rebounds_per_game: "10.8",
    assists_per_game: "1.1",
    steals_per_game: "0.8",
    blocks_per_game: "1.7",
    turnovers_per_game: "1.6",
    player_efficiency_rating: "2.8",
  },
  {
    name: "Demetrius Jackson",
    team_acronym: "hou",
    team_name: "Houston",
    games_played: "12",
    minutes_per_game: "5:12",
    field_goals_attempted_per_game: "1.2",
    field_goals_made_per_game: "0.3",
    field_goal_percentage: "28.6",
    free_throw_percentage: "0.0",
    three_point_attempted_per_game: "0.5",
    three_point_made_per_game: "0.0",
    three_point_percentage: "0.0",
    points_per_game: "0.7",
    offensive_rebounds_per_game: "0.3",
    defensive_rebounds_per_game: "0.6",
    rebounds_per_game: "0.9",
    assists_per_game: "0.4",
    steals_per_game: "0.3",
    blocks_per_game: "0.1",
    turnovers_per_game: "0.8",
    player_efficiency_rating: "0.5",
  },
  {
    name: "Eric Gordon",
    team_acronym: "hou",
    team_name: "Houston",
    games_played: "44",
    minutes_per_game: "32:39",
    field_goals_attempted_per_game: "15.5",
    field_goals_made_per_game: "6.5",
    field_goal_percentage: "41.8",
    free_throw_percentage: "82.1",
    three_point_attempted_per_game: "9.5",
    three_point_made_per_game: "3.2",
    three_point_percentage: "33.4",
    points_per_game: "19.5",
    offensive_rebounds_per_game: "0.4",
    defensive_rebounds_per_game: "2.0",
    rebounds_per_game: "2.4",
    assists_per_game: "2.6",
    steals_per_game: "0.7",
    blocks_per_game: "0.3",
    turnovers_per_game: "2.2",
    player_efficiency_rating: "1.8",
  },
  {
    name: "Gerald Green",
    team_acronym: "hou",
    team_name: "Houston",
    games_played: "11",
    minutes_per_game: "24:39",
    field_goals_attempted_per_game: "11.0",
    field_goals_made_per_game: "4.7",
    field_goal_percentage: "43.0",
    free_throw_percentage: "81.8",
    three_point_attempted_per_game: "7.5",
    three_point_made_per_game: "3.1",
    three_point_percentage: "41.0",
    points_per_game: "14.2",
    offensive_rebounds_per_game: "0.5",
    defensive_rebounds_per_game: "2.5",
    rebounds_per_game: "2.9",
    assists_per_game: "0.8",
    steals_per_game: "0.6",
    blocks_per_game: "0.3",
    turnovers_per_game: "0.9",
    player_efficiency_rating: "2.2",
  },
  {
    name: "Isaiah Canaan",
    team_acronym: "hou",
    team_name: "Houston",
    games_played: "1",
    minutes_per_game: "3:57",
    field_goals_attempted_per_game: "1.0",
    field_goals_made_per_game: "0.0",
    field_goal_percentage: "0.0",
    free_throw_percentage: "0.0",
    three_point_attempted_per_game: "0.0",
    three_point_made_per_game: "0.0",
    three_point_percentage: "0.0",
    points_per_game: "0.0",
    offensive_rebounds_per_game: "0.0",
    defensive_rebounds_per_game: "1.0",
    rebounds_per_game: "1.0",
    assists_per_game: "0.0",
    steals_per_game: "0.0",
    blocks_per_game: "0.0",
    turnovers_per_game: "0.0",
    player_efficiency_rating: "0.0",
  },
  {
    name: "James Harden",
    team_acronym: "hou",
    team_name: "Houston",
    games_played: "39",
    minutes_per_game: "35:49",
    field_goals_attempted_per_game: "20.9",
    field_goals_made_per_game: "9.3",
    field_goal_percentage: "44.7",
    free_throw_percentage: "86.3",
    three_point_attempted_per_game: "10.5",
    three_point_made_per_game: "4.2",
    three_point_percentage: "39.6",
    points_per_game: "31.2",
    offensive_rebounds_per_game: "0.5",
    defensive_rebounds_per_game: "4.3",
    rebounds_per_game: "4.8",
    assists_per_game: "9.0",
    steals_per_game: "1.8",
    blocks_per_game: "0.7",
    turnovers_per_game: "4.3",
    player_efficiency_rating: "2.5",
  },
  {
    name: "Luc Richard Mbah a Moute",
    team_acronym: "hou",
    team_name: "Houston",
    games_played: "29",
    minutes_per_game: "25:35",
    field_goals_attempted_per_game: "5.6",
    field_goals_made_per_game: "2.5",
    field_goal_percentage: "45.3",
    free_throw_percentage: "69.7",
    three_point_attempted_per_game: "2.9",
    three_point_made_per_game: "1.1",
    three_point_percentage: "37.6",
    points_per_game: "6.9",
    offensive_rebounds_per_game: "0.5",
    defensive_rebounds_per_game: "2.9",
    rebounds_per_game: "3.4",
    assists_per_game: "1.0",
    steals_per_game: "1.3",
    blocks_per_game: "0.4",
    turnovers_per_game: "1.3",
    player_efficiency_rating: "1.8",
  },
  {
    name: "Nene Hilario",
    team_acronym: "hou",
    team_name: "Houston",
    games_played: "30",
    minutes_per_game: "14:57",
    field_goals_attempted_per_game: "4.9",
    field_goals_made_per_game: "2.9",
    field_goal_percentage: "59.9",
    free_throw_percentage: "67.2",
    three_point_attempted_per_game: "0.1",
    three_point_made_per_game: "0.0",
    three_point_percentage: "0.0",
    points_per_game: "7.3",
    offensive_rebounds_per_game: "1.0",
    defensive_rebounds_per_game: "2.4",
    rebounds_per_game: "3.4",
    assists_per_game: "0.9",
    steals_per_game: "0.5",
    blocks_per_game: "0.3",
    turnovers_per_game: "0.8",
    player_efficiency_rating: "2.6",
  },
  {
    name: "P.J. Tucker",
    team_acronym: "hou",
    team_name: "Houston",
    games_played: "46",
    minutes_per_game: "26:51",
    field_goals_attempted_per_game: "4.9",
    field_goals_made_per_game: "1.9",
    field_goal_percentage: "38.2",
    free_throw_percentage: "80.0",
    three_point_attempted_per_game: "3.2",
    three_point_made_per_game: "1.1",
    three_point_percentage: "34.5",
    points_per_game: "5.5",
    offensive_rebounds_per_game: "1.2",
    defensive_rebounds_per_game: "4.8",
    rebounds_per_game: "6.0",
    assists_per_game: "0.8",
    steals_per_game: "1.0",
    blocks_per_game: "0.3",
    turnovers_per_game: "0.9",
    player_efficiency_rating: "2.7",
  },
  {
    name: "R.J. Hunter",
    team_acronym: "hou",
    team_name: "Houston",
    games_played: "2",
    minutes_per_game: "0:49",
    field_goals_attempted_per_game: "0.0",
    field_goals_made_per_game: "0.0",
    field_goal_percentage: "0.0",
    free_throw_percentage: "0.0",
    three_point_attempted_per_game: "0.0",
    three_point_made_per_game: "0.0",
    three_point_percentage: "0.0",
    points_per_game: "0.0",
    offensive_rebounds_per_game: "0.0",
    defensive_rebounds_per_game: "0.5",
    rebounds_per_game: "0.5",
    assists_per_game: "1.0",
    steals_per_game: "0.0",
    blocks_per_game: "0.0",
    turnovers_per_game: "0.0",
    player_efficiency_rating: "0.0",
  },
  {
    name: "Ryan Anderson",
    team_acronym: "hou",
    team_name: "Houston",
    games_played: "45",
    minutes_per_game: "28:39",
    field_goals_attempted_per_game: "8.1",
    field_goals_made_per_game: "3.4",
    field_goal_percentage: "42.7",
    free_throw_percentage: "78.1",
    three_point_attempted_per_game: "5.7",
    three_point_made_per_game: "2.1",
    three_point_percentage: "37.0",
    points_per_game: "10.1",
    offensive_rebounds_per_game: "1.6",
    defensive_rebounds_per_game: "4.0",
    rebounds_per_game: "5.6",
    assists_per_game: "1.0",
    steals_per_game: "0.5",
    blocks_per_game: "0.4",
    turnovers_per_game: "0.8",
    player_efficiency_rating: "1.9",
  },
  {
    name: "Tarik Black",
    team_acronym: "hou",
    team_name: "Houston",
    games_played: "34",
    minutes_per_game: "10:05",
    field_goals_attempted_per_game: "2.6",
    field_goals_made_per_game: "1.5",
    field_goal_percentage: "56.7",
    free_throw_percentage: "46.7",
    three_point_attempted_per_game: "0.2",
    three_point_made_per_game: "0.0",
    three_point_percentage: "0.0",
    points_per_game: "3.6",
    offensive_rebounds_per_game: "1.3",
    defensive_rebounds_per_game: "1.8",
    rebounds_per_game: "3.0",
    assists_per_game: "0.2",
    steals_per_game: "0.4",
    blocks_per_game: "0.5",
    turnovers_per_game: "0.8",
    player_efficiency_rating: "2.1",
  },
  {
    name: "Trevor Ariza",
    team_acronym: "hou",
    team_name: "Houston",
    games_played: "42",
    minutes_per_game: "35:55",
    field_goals_attempted_per_game: "9.8",
    field_goals_made_per_game: "4.2",
    field_goal_percentage: "42.6",
    free_throw_percentage: "87.9",
    three_point_attempted_per_game: "7.3",
    three_point_made_per_game: "2.8",
    three_point_percentage: "38.4",
    points_per_game: "12.4",
    offensive_rebounds_per_game: "0.6",
    defensive_rebounds_per_game: "4.3",
    rebounds_per_game: "4.8",
    assists_per_game: "1.7",
    steals_per_game: "1.6",
    blocks_per_game: "0.2",
    turnovers_per_game: "0.9",
    player_efficiency_rating: "1.9",
  },
  {
    name: "Troy Williams",
    team_acronym: "hou",
    team_name: "Houston",
    games_played: "4",
    minutes_per_game: "4:14",
    field_goals_attempted_per_game: "2.3",
    field_goals_made_per_game: "0.5",
    field_goal_percentage: "22.2",
    free_throw_percentage: "33.3",
    three_point_attempted_per_game: "1.3",
    three_point_made_per_game: "0.0",
    three_point_percentage: "0.0",
    points_per_game: "1.3",
    offensive_rebounds_per_game: "0.3",
    defensive_rebounds_per_game: "0.8",
    rebounds_per_game: "1.0",
    assists_per_game: "0.3",
    steals_per_game: "0.3",
    blocks_per_game: "0.0",
    turnovers_per_game: "0.3",
    player_efficiency_rating: "0.5",
  },
  {
    name: "Zhou Qi",
    team_acronym: "hou",
    team_name: "Houston",
    games_played: "14",
    minutes_per_game: "5:23",
    field_goals_attempted_per_game: "1.7",
    field_goals_made_per_game: "0.3",
    field_goal_percentage: "16.7",
    free_throw_percentage: "70.0",
    three_point_attempted_per_game: "1.1",
    three_point_made_per_game: "0.1",
    three_point_percentage: "13.3",
    points_per_game: "1.2",
    offensive_rebounds_per_game: "0.1",
    defensive_rebounds_per_game: "0.8",
    rebounds_per_game: "0.9",
    assists_per_game: "0.1",
    steals_per_game: "0.1",
    blocks_per_game: "0.4",
    turnovers_per_game: "0.4",
    player_efficiency_rating: "0.9",
  },
    {
      name: "Abdel Nader",
      team_acronym: "bos",
      team_name: "Boston",
      games_played: "22",
      minutes_per_game: "7:26",
      field_goals_attempted_per_game: "2.1",
      field_goals_made_per_game: "0.7",
      field_goal_percentage: "34.8",
      free_throw_percentage: "33.3",
      three_point_attempted_per_game: "1.1",
      three_point_made_per_game: "0.4",
      three_point_percentage: "33.3",
      points_per_game: "1.9",
      offensive_rebounds_per_game: "0.2",
      defensive_rebounds_per_game: "0.7",
      rebounds_per_game: "1.0",
      assists_per_game: "0.3",
      steals_per_game: "0.2",
      blocks_per_game: "0.2",
      turnovers_per_game: "0.4",
      player_efficiency_rating: "0.6",
    },
    {
      name: "Al Horford",
      team_acronym: "bos",
      team_name: "Boston",
      games_played: "44",
      minutes_per_game: "32:39",
      field_goals_attempted_per_game: "10.5",
      field_goals_made_per_game: "5.4",
      field_goal_percentage: "51.3",
      free_throw_percentage: "72.5",
      three_point_attempted_per_game: "3.3",
      three_point_made_per_game: "1.5",
      three_point_percentage: "43.5",
      points_per_game: "13.3",
      offensive_rebounds_per_game: "1.5",
      defensive_rebounds_per_game: "6.3",
      rebounds_per_game: "7.8",
      assists_per_game: "5.3",
      steals_per_game: "0.6",
      blocks_per_game: "1.1",
      turnovers_per_game: "1.9",
      player_efficiency_rating: "1.9",
    },
    {
      name: "Aron Baynes",
      team_acronym: "bos",
      team_name: "Boston",
      games_played: "49",
      minutes_per_game: "18:03",
      field_goals_attempted_per_game: "5.1",
      field_goals_made_per_game: "2.4",
      field_goal_percentage: "47.6",
      free_throw_percentage: "73.7",
      three_point_attempted_per_game: "0.2",
      three_point_made_per_game: "0.0",
      three_point_percentage: "0.0",
      points_per_game: "5.8",
      offensive_rebounds_per_game: "1.5",
      defensive_rebounds_per_game: "3.6",
      rebounds_per_game: "5.1",
      assists_per_game: "0.9",
      steals_per_game: "0.3",
      blocks_per_game: "0.6",
      turnovers_per_game: "1.0",
      player_efficiency_rating: "2.5",
    },
    {
      name: "Daniel Theis",
      team_acronym: "bos",
      team_name: "Boston",
      games_played: "47",
      minutes_per_game: "13:38",
      field_goals_attempted_per_game: "3.4",
      field_goals_made_per_game: "1.8",
      field_goal_percentage: "52.5",
      free_throw_percentage: "78.6",
      three_point_attempted_per_game: "0.8",
      three_point_made_per_game: "0.2",
      three_point_percentage: "28.2",
      points_per_game: "4.8",
      offensive_rebounds_per_game: "1.3",
      defensive_rebounds_per_game: "3.0",
      rebounds_per_game: "4.3",
      assists_per_game: "0.7",
      steals_per_game: "0.5",
      blocks_per_game: "0.7",
      turnovers_per_game: "1.0",
      player_efficiency_rating: "2.4",
    },
    {
      name: "Gordon Hayward",
      team_acronym: "bos",
      team_name: "Boston",
      games_played: "1",
      minutes_per_game: "5:15",
      field_goals_attempted_per_game: "2.0",
      field_goals_made_per_game: "1.0",
      field_goal_percentage: "50.0",
      free_throw_percentage: "0.0",
      three_point_attempted_per_game: "1.0",
      three_point_made_per_game: "0.0",
      three_point_percentage: "0.0",
      points_per_game: "2.0",
      offensive_rebounds_per_game: "0.0",
      defensive_rebounds_per_game: "1.0",
      rebounds_per_game: "1.0",
      assists_per_game: "0.0",
      steals_per_game: "0.0",
      blocks_per_game: "0.0",
      turnovers_per_game: "0.0",
      player_efficiency_rating: "1.0",
    },
    {
      name: "Guerschon Yabusele",
      team_acronym: "bos",
      team_name: "Boston",
      games_played: "18",
      minutes_per_game: "4:42",
      field_goals_attempted_per_game: "1.5",
      field_goals_made_per_game: "0.6",
      field_goal_percentage: "40.7",
      free_throw_percentage: "100.0",
      three_point_attempted_per_game: "1.0",
      three_point_made_per_game: "0.4",
      three_point_percentage: "38.9",
      points_per_game: "1.7",
      offensive_rebounds_per_game: "0.6",
      defensive_rebounds_per_game: "0.8",
      rebounds_per_game: "1.4",
      assists_per_game: "0.3",
      steals_per_game: "0.0",
      blocks_per_game: "0.1",
      turnovers_per_game: "0.3",
      player_efficiency_rating: "0.7",
    },
    {
      name: "Jabari Bird",
      team_acronym: "bos",
      team_name: "Boston",
      games_played: "4",
      minutes_per_game: "5:36",
      field_goals_attempted_per_game: "1.0",
      field_goals_made_per_game: "0.3",
      field_goal_percentage: "25.0",
      free_throw_percentage: "60.0",
      three_point_attempted_per_game: "0.5",
      three_point_made_per_game: "0.0",
      three_point_percentage: "0.0",
      points_per_game: "1.3",
      offensive_rebounds_per_game: "0.0",
      defensive_rebounds_per_game: "0.5",
      rebounds_per_game: "0.5",
      assists_per_game: "0.3",
      steals_per_game: "0.3",
      blocks_per_game: "0.0",
      turnovers_per_game: "0.0",
      player_efficiency_rating: "0.5",
    },
    {
      name: "Jarell Eddie",
      team_acronym: "bos",
      team_name: "Boston",
      games_played: "2",
      minutes_per_game: "2:49",
      field_goals_attempted_per_game: "0.5",
      field_goals_made_per_game: "0.0",
      field_goal_percentage: "0.0",
      free_throw_percentage: "0.0",
      three_point_attempted_per_game: "0.5",
      three_point_made_per_game: "0.0",
      three_point_percentage: "0.0",
      points_per_game: "0.0",
      offensive_rebounds_per_game: "0.0",
      defensive_rebounds_per_game: "0.5",
      rebounds_per_game: "0.5",
      assists_per_game: "0.0",
      steals_per_game: "0.5",
      blocks_per_game: "0.0",
      turnovers_per_game: "0.0",
      player_efficiency_rating: "0.0",
    },
    {
      name: "Jaylen Brown",
      team_acronym: "bos",
      team_name: "Boston",
      games_played: "44",
      minutes_per_game: "31:21",
      field_goals_attempted_per_game: "11.4",
      field_goals_made_per_game: "5.2",
      field_goal_percentage: "45.8",
      free_throw_percentage: "58.1",
      three_point_attempted_per_game: "4.5",
      three_point_made_per_game: "1.7",
      three_point_percentage: "37.2",
      points_per_game: "14.0",
      offensive_rebounds_per_game: "1.1",
      defensive_rebounds_per_game: "4.5",
      rebounds_per_game: "5.6",
      assists_per_game: "1.5",
      steals_per_game: "1.1",
      blocks_per_game: "0.4",
      turnovers_per_game: "1.7",
      player_efficiency_rating: "2.8",
    },
    {
      name: "Jayson Tatum",
      team_acronym: "bos",
      team_name: "Boston",
      games_played: "49",
      minutes_per_game: "31:02",
      field_goals_attempted_per_game: "9.6",
      field_goals_made_per_game: "4.7",
      field_goal_percentage: "48.6",
      free_throw_percentage: "81.5",
      three_point_attempted_per_game: "3.1",
      three_point_made_per_game: "1.4",
      three_point_percentage: "45.0",
      points_per_game: "13.6",
      offensive_rebounds_per_game: "0.8",
      defensive_rebounds_per_game: "4.7",
      rebounds_per_game: "5.5",
      assists_per_game: "1.3",
      steals_per_game: "0.9",
      blocks_per_game: "0.8",
      turnovers_per_game: "1.4",
      player_efficiency_rating: "2.2",
    },
    {
      name: "Kadeem Allen",
      team_acronym: "bos",
      team_name: "Boston",
      games_played: "3",
      minutes_per_game: "2:43",
      field_goals_attempted_per_game: "0.7",
      field_goals_made_per_game: "0.0",
      field_goal_percentage: "0.0",
      free_throw_percentage: "75.0",
      three_point_attempted_per_game: "0.7",
      three_point_made_per_game: "0.0",
      three_point_percentage: "0.0",
      points_per_game: "1.0",
      offensive_rebounds_per_game: "0.3",
      defensive_rebounds_per_game: "0.3",
      rebounds_per_game: "0.7",
      assists_per_game: "0.0",
      steals_per_game: "0.0",
      blocks_per_game: "0.0",
      turnovers_per_game: "0.3",
      player_efficiency_rating: "0.0",
    },
    {
      name: "Kyrie Irving",
      team_acronym: "bos",
      team_name: "Boston",
      games_played: "46",
      minutes_per_game: "32:54",
      field_goals_attempted_per_game: "18.8",
      field_goals_made_per_game: "9.0",
      field_goal_percentage: "47.7",
      free_throw_percentage: "88.8",
      three_point_attempted_per_game: "6.8",
      three_point_made_per_game: "2.7",
      three_point_percentage: "39.3",
      points_per_game: "24.5",
      offensive_rebounds_per_game: "0.6",
      defensive_rebounds_per_game: "3.2",
      rebounds_per_game: "3.8",
      assists_per_game: "5.0",
      steals_per_game: "1.2",
      blocks_per_game: "0.3",
      turnovers_per_game: "2.3",
      player_efficiency_rating: "2.1",
    },
    {
      name: "Marcus Morris",
      team_acronym: "bos",
      team_name: "Boston",
      games_played: "27",
      minutes_per_game: "23:56",
      field_goals_attempted_per_game: "10.1",
      field_goals_made_per_game: "4.2",
      field_goal_percentage: "41.9",
      free_throw_percentage: "81.5",
      three_point_attempted_per_game: "4.0",
      three_point_made_per_game: "1.3",
      three_point_percentage: "33.6",
      points_per_game: "11.7",
      offensive_rebounds_per_game: "0.7",
      defensive_rebounds_per_game: "4.5",
      rebounds_per_game: "5.3",
      assists_per_game: "1.4",
      steals_per_game: "0.5",
      blocks_per_game: "0.3",
      turnovers_per_game: "1.2",
      player_efficiency_rating: "1.9",
    },
    {
      name: "Marcus Smart",
      team_acronym: "bos",
      team_name: "Boston",
      games_played: "46",
      minutes_per_game: "30:16",
      field_goals_attempted_per_game: "9.7",
      field_goals_made_per_game: "3.5",
      field_goal_percentage: "35.7",
      free_throw_percentage: "73.6",
      three_point_attempted_per_game: "4.6",
      three_point_made_per_game: "1.4",
      three_point_percentage: "29.9",
      points_per_game: "10.1",
      offensive_rebounds_per_game: "0.8",
      defensive_rebounds_per_game: "2.8",
      rebounds_per_game: "3.6",
      assists_per_game: "4.7",
      steals_per_game: "1.3",
      blocks_per_game: "0.5",
      turnovers_per_game: "2.5",
      player_efficiency_rating: "2.7",
    },
    {
      name: "Semi Ojeleye",
      team_acronym: "bos",
      team_name: "Boston",
      games_played: "43",
      minutes_per_game: "13:06",
      field_goals_attempted_per_game: "2.3",
      field_goals_made_per_game: "0.7",
      field_goal_percentage: "32.0",
      free_throw_percentage: "61.9",
      three_point_attempted_per_game: "1.8",
      three_point_made_per_game: "0.5",
      three_point_percentage: "29.5",
      points_per_game: "2.3",
      offensive_rebounds_per_game: "0.5",
      defensive_rebounds_per_game: "1.4",
      rebounds_per_game: "1.9",
      assists_per_game: "0.2",
      steals_per_game: "0.3",
      blocks_per_game: "0.0",
      turnovers_per_game: "0.3",
      player_efficiency_rating: "1.1",
    },
    {
      name: "Shane Larkin",
      team_acronym: "bos",
      team_name: "Boston",
      games_played: "36",
      minutes_per_game: "11:26",
      field_goals_attempted_per_game: "3.2",
      field_goals_made_per_game: "1.3",
      field_goal_percentage: "39.1",
      free_throw_percentage: "86.4",
      three_point_attempted_per_game: "1.3",
      three_point_made_per_game: "0.5",
      three_point_percentage: "36.2",
      points_per_game: "3.5",
      offensive_rebounds_per_game: "0.2",
      defensive_rebounds_per_game: "1.0",
      rebounds_per_game: "1.2",
      assists_per_game: "1.1",
      steals_per_game: "0.3",
      blocks_per_game: "0.1",
      turnovers_per_game: "0.4",
      player_efficiency_rating: "1.0",
    },
    {
      name: "Terry Rozier",
      team_acronym: "bos",
      team_name: "Boston",
      games_played: "49",
      minutes_per_game: "23:00",
      field_goals_attempted_per_game: "8.5",
      field_goals_made_per_game: "3.3",
      field_goal_percentage: "39.1",
      free_throw_percentage: "81.0",
      three_point_attempted_per_game: "4.3",
      three_point_made_per_game: "1.5",
      three_point_percentage: "34.6",
      points_per_game: "9.1",
      offensive_rebounds_per_game: "0.6",
      defensive_rebounds_per_game: "3.7",
      rebounds_per_game: "4.3",
      assists_per_game: "2.0",
      steals_per_game: "1.0",
      blocks_per_game: "0.1",
      turnovers_per_game: "0.8",
      player_efficiency_rating: "1.3",
    },
];
 export default teams;